@startuml deployement
!theme aws-orange

rectangle "Deployment Diagram" {
    database "ProductionDB\n(MySQL)\nport 3306" as sqldatabase
    database "HistoryDB\n(MongoDB)\nport 27017" as nosqldatabase

    cloud "sql-network\n(port 3306)" as sqlnet
    cloud "nosql-network\n(port 27017)" as nosqlnet
    cloud "ws-network\n(port 1883 / 8080)" as wsnet
    cloud "front-network\n(port 80 / 443)" as frontnet

    node "MOM Broker\n(port 1883 / 8080)" as broker 
    node "HTTP Server\n(port 80)" as front
    node "webapp\n(Node.js >= 22)\n[profile: build-only]\n(port 3000)" as webappbuild
    node "phpMyAdmin\n(port 80)" as pma
    node "mongo-express\n(port 80)" as mex
    node "REST API\n(port 8080)" as restapi
    node "RealTime API\n(port 8081)" as wsapi
}

circle "Users\nhttp://localhost:80" as users
circle "Access admin pma\nhttp://localhost:8888 → :80" as accesspma
circle "Access admin mex\nhttp://localhost:8889 → :80" as accessmex

' --- Frontend connections ---
front -down- frontnet : serve :80
frontnet -down- wsapi : serve :8081
frontnet -down- restapi : serve :8080

' --- Databases ---
sqlnet -down- sqldatabase : port 3306
nosqlnet -down- nosqldatabase : port 27017

' --- APIs access databases ---
wsapi -down- sqlnet : read/write :3306
wsapi -down- nosqlnet : read/write :27017
restapi -down- sqlnet : read/write :3306
restapi -down- nosqlnet : read/write :27017

' --- Messaging ---
restapi -up- wsnet : publish/subscribe :1883
wsnet -up- broker : publish/subscribe :1883
broker -up- accessBroker : Access admin http://localhost:15672

' --- Admin tools ---
pma -up- sqlnet : manage :3306
mex -up- nosqlnet : manage :27017

pma -down- accesspma : web :80→8888
mex -down- accessmex : web :80→8889
front -right- users : web :80
@enduml

@startuml Volume_deployement
!theme aws-orange  
rectangle "Volumes" {
        folder "Persistent data volumes" {
            storage "sqldata\n(logistico_sql_data)" as v_sqldata
            storage "nosqldata\n(logistico_nosql_data)" as v_nosqldata
            storage "nosqlconfig\n(logistico_nosql_config)" as v_nosqlconfig
            storage "brokerdata\n(logistico_broker_data)" as v_brokerdata
            storage "webapp-build\n(logistico_webapp_build)" as v_webappbuild
        }

        v_sqldata -down- "sqldatabase : /var/lib/mysql"
        v_nosqldata -down- "nosqldatabase : /data/db"
        v_nosqlconfig -down- "nosqldatabase : /data/configdb"
        v_brokerdata -down- "broker : /var/lib/rabbitmq"

        folder "Mounts for configuration files" {
            file "sql-init" as f_sqlinit
            file "nginx-conf" as f_nginx
        }
        f_sqlinit -down- "sqldatabase : /docker-entrypoint-initdb.d/init.sql"
        f_nginx -down- "front : /etc/nginx/nginx.conf"
}

@enduml
